import test from 'node:test';import assert from 'node:assert/strict';import {handle,aggregate,validatePosition,normalizeTrip} from '../backend/core.mjs';import {MemoryStore} from '../backend/store.mjs';import {predict,snap,along,metres} from '../web/motion.mjs';
const now=Date.UTC(2026,9,1,12),env={ADMIN_KEY:'test-admin-secret'};
const req=(path,b,token,method=b?'POST':'GET')=>new Request('https://test.local'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(b?{body:JSON.stringify(b)}:{})});
async function setup(){const s=new MemoryStore(),t=await handle(req('/api/admin/trips',{train:'12915',date:'2026-10-01',name:'Test journey'},env.ADMIN_KEY),s,env,now);const session=await handle(req('/api/join',{tripId:t.id,code:t.contributorCode}),s,env,now);return {s,t,token:session.token}}
const pos=(t=now,lon=77.2)=>({lat:28.6,lon,accuracy:10,timestamp:t,speed:20,bearing:90});
test('journey creation needs admin secret and valid date',async()=>{await assert.rejects(handle(req('/api/admin/trips',{train:'12915',date:'2026-10-01',name:'x'}),new MemoryStore(),env,now),e=>e.status===401);assert.throws(()=>normalizeTrip({train:'12915',date:'2026-02-30',name:'x'},now));});
test('observer can find a journey without contributor credentials',async()=>{const {s,t}=await setup();const found=await handle(req('/api/trips?train=12915&date=2026-10-01'),s,env,now);assert.equal(found.id,t.id);assert.equal(found.codeHash,undefined)});
test('wrong contributor code rejected',async()=>{const {s,t}=await setup();await assert.rejects(handle(req('/api/join',{tripId:t.id,code:'wrong'}),s,env,now),e=>e.status===403)});
test('contribution visible, 15-second limit enforced, secrets omitted',async()=>{const {s,t,token}=await setup();await handle(req('/api/positions',pos(),token),s,env,now);const x=await handle(req('/api/state?tripId='+t.id),s,env,now+1000);assert.equal(x.quality,'single-contributor');assert.equal(x.position.tokenHash,undefined);await assert.rejects(handle(req('/api/positions',pos(now+1000),token),s,env,now+1000),e=>e.status===429);await handle(req('/api/positions',pos(now+15000,77.202),token),s,env,now+15000)});
test('simultaneous uploads reserve only one slot',async()=>{const {s,token}=await setup();const results=await Promise.allSettled([handle(req('/api/positions',pos(),token),s,env,now),handle(req('/api/positions',pos(),token),s,env,now)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1)});
test('poor accuracy, old timestamp and impossible speed rejected',()=>{for(const p of [{...pos(),accuracy:500},{...pos(),timestamp:now-120000},{...pos(),speed:200},{...pos(),lat:100}])assert.throws(()=>validatePosition(p,now))});
test('teleport rejected and slot remains usable for correct position',async()=>{const {s,token}=await setup();await handle(req('/api/positions',pos(),token),s,env,now);await assert.rejects(handle(req('/api/positions',pos(now+15000,80),token),s,env,now+15000),e=>e.status===400);await handle(req('/api/positions',pos(now+15000,77.202),token),s,env,now+15000)});
test('stop removes contributor and immediately revokes token',async()=>{const {s,t,token}=await setup();await handle(req('/api/positions',pos(),token),s,env,now);await handle(req('/api/session',null,token,'DELETE'),s,env,now);assert.equal((await handle(req('/api/state?tripId='+t.id),s,env,now)).position,null);await assert.rejects(handle(req('/api/positions',pos(),token),s,env,now),e=>e.status===401)});
test('stale and expired reports change quality; expired journey unavailable',async()=>{const {s,t,token}=await setup();await handle(req('/api/positions',pos(),token),s,env,now);assert.equal((await handle(req('/api/state?tripId='+t.id),s,env,now+60000)).quality,'stale');assert.equal((await handle(req('/api/state?tripId='+t.id),s,env,now+121000)).quality,'unavailable');await assert.rejects(handle(req('/api/state?tripId='+t.id),s,env,now+86400001),e=>e.status===404)});
test('conflicting contributors do not fabricate a midpoint',()=>{const a={...pos(),receivedAt:now},b={...a,lon:79};assert.equal(aggregate([a,b],now).quality,'conflicting');const c={...a,lon:77.2001};assert.equal(aggregate([a,b,c],now).contributors,2)});
test('animation follows a curved route and freezes after 30 seconds',()=>{const route=[[77,28],[77.001,28],[77.001,28.01]],p={lat:28,lon:77,accuracy:10,speed:20,bearing:90,timestamp:now};const a=predict(p,route,now+30000),b=predict(p,route,now+120000);assert.deepEqual(a.point,b.point);assert.equal(a.point[0],77.001);assert.ok(a.point[1]>28);assert.ok(snap(route,[77.0005,28]).distance<1);assert.deepEqual(along(route,1e6).point,route.at(-1))});
test('unknown speed does not invent movement, distant route does not snap GPS',()=>{const p={...pos(),speed:null};assert.ok(metres(predict(p,null,now+15000).point,[p.lon,p.lat])<.01);const route=[[80,20],[81,20]];assert.ok(metres(predict(p,route,now).point,[p.lon,p.lat])<.01)});

test('repeated route coordinates do not break stationary markers',()=>{const a=along([[77,28],[77,28],[77.01,28]],0);assert.deepEqual(a.point,[77,28]);assert.ok(Number.isFinite(a.bearing))});

test('unknown heading without a route does not invent northward motion',()=>{const p={...pos(),bearing:null};assert.ok(metres(predict(p,null,now+15000).point,[p.lon,p.lat])<.01)});
