// Run with: NODE_PATH=<path containing linkedom> node --test test/ui.test.mjs
// Optional DOM smoke test; excluded from default test command if linkedom absent.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';
import {handle} from '../backend/core.mjs';import {MemoryStore} from '../backend/store.mjs';
let parseHTML;try{({parseHTML}=createRequire(import.meta.url)(process.env.DOM_TEST_MODULE||'linkedom'))}catch{}
test('interface demo, language, consent and contributor-observer workflow',{skip:!parseHTML},async()=>{
 const {window,document}=parseHTML(fs.readFileSync(new URL('../web/index.html',import.meta.url),'utf8'));globalThis.window=window;globalThis.document=document;const frames=[];globalThis.requestAnimationFrame=f=>frames.push(f);globalThis.devicePixelRatio=1;globalThis.ResizeObserver=class{constructor(fn){this.fn=fn}observe(){this.fn()}};globalThis.Image=class{complete=false};document.getElementById('map').getBoundingClientRect=()=>({width:390,height:844});document.getElementById('map').getContext=()=>new Proxy({},{get:()=>()=>{}});const memory=new Map();globalThis.localStorage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};globalThis.location={origin:'https://test.local',search:''};globalThis.history={replaceState(){}};Object.defineProperty(globalThis,'navigator',{value:{geolocation:{watchPosition(f){f({coords:{latitude:28.6,longitude:77.2,accuracy:10,speed:20,heading:90},timestamp:Date.now()});return 1},clearWatch(){}}},configurable:true});
 for(const d of document.querySelectorAll('dialog')){d.showModal=()=>d.setAttribute('open','');d.close=()=>d.removeAttribute('open')}
 const store=new MemoryStore(),env={ADMIN_KEY:'ui-test'},t=await handle(new Request('https://test.local/api/admin/trips',{method:'POST',headers:{Authorization:'Bearer ui-test','Content-Type':'application/json'},body:JSON.stringify({train:'12915',date:'2026-10-01',name:'UI pilot'})}),store,env);
 const timers=[];const originalInterval=globalThis.setInterval;globalThis.setInterval=(fn)=>{timers.push(fn);return timers.length};globalThis.clearInterval=()=>{};
 const originalFetch=globalThis.fetch;globalThis.fetch=async(path,init={})=>{try{return new Response(JSON.stringify(await handle(new Request(new URL(path,'https://test.local'),init),store,env)),{status:200})}catch(e){return new Response(JSON.stringify({error:e.message}),{status:e.status||500})}};
 try{await import('../web/app.mjs');const $=id=>document.getElementById(id);$('demo').onclick();assert.equal($('demo-tag').hidden,false);$('language').onclick();assert.equal($('onboard').textContent,'मैं इस ट्रेन में हूँ');$('demo').onclick();$('onboard').onclick();assert.match($('toast').textContent,/Select/);$('train').value='12915';$('date').value='2026-10-01';await $('search-form').onsubmit({preventDefault(){},submitter:{disabled:false}});assert.equal($('journey-name').textContent,'UI pilot');$('onboard').onclick();assert.ok($('join-dialog').hasAttribute('open'));await $('start-sharing').onclick();assert.match($('toast').textContent,/agree/);$('consent').checked=true;$('code').value=t.contributorCode;await $('start-sharing').onclick();await new Promise(r=>setTimeout(r,30));assert.equal($('sharing').hidden,false);assert.equal((await store.observations(t.id)).length,1);await $('stop').onclick();assert.equal((await store.observations(t.id)).length,0);assert.equal($('sharing').hidden,true)}finally{globalThis.fetch=originalFetch;globalThis.setInterval=originalInterval}
});
