package in.railsaathi.app;
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.webkit.*;import android.net.Uri;import java.io.*;import java.util.*;import org.json.JSONObject;
public class MainActivity extends Activity {
 private WebView web;private Intent pending;private final Handler handler=new Handler(Looper.getMainLooper());
 private final Runnable status=new Runnable(){public void run(){if(web!=null){boolean running=TrackingService.running;String text=getSharedPreferences("tracking",0).getString("status","Sharing stopped");web.evaluateJavascript("window.nativeSharingStatus&&window.nativeSharingStatus("+running+","+JSONObject.quote(text)+")",null);}handler.postDelayed(this,4000);}};
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xff086e66);web=new WebView(this);setContentView(web);if(Build.VERSION.SDK_INT>=30)web.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets bars=insets.getInsets(android.view.WindowInsets.Type.systemBars());v.setPadding(bars.left,bars.top,bars.right,bars.bottom);return insets;});WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setUserAgentString("RailSaathi/0.2 (Android) "+s.getUserAgentString());web.addJavascriptInterface(new Bridge(),"Android");web.setWebViewClient(new WebViewClient(){
 @Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest req){Uri u=req.getUrl();if(!"appassets.androidplatform.net".equals(u.getHost()))return null;String p=u.getPath();if(p==null||p.equals("/"))p="/index.html";if(p.contains(".."))return new WebResourceResponse("text/plain","UTF-8",403,"Forbidden",Collections.emptyMap(),new ByteArrayInputStream(new byte[0]));try{String mime=p.endsWith(".html")?"text/html":p.endsWith(".css")?"text/css":p.endsWith(".mjs")||p.endsWith(".js")?"text/javascript":p.endsWith(".svg")?"image/svg+xml":"application/json";return new WebResourceResponse(mime,"UTF-8",200,"OK",Collections.singletonMap("Cache-Control","no-cache"),getAssets().open(p.substring(1)));}catch(IOException e){return new WebResourceResponse("text/plain","UTF-8",404,"Not Found",Collections.emptyMap(),new ByteArrayInputStream(new byte[0]));}}
 @Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest req){Uri u=req.getUrl();if("appassets.androidplatform.net".equals(u.getHost()))return false;if("https".equals(u.getScheme())){try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception ignored){}}return true;}
 });web.loadUrl("https://appassets.androidplatform.net/index.html");}
 @Override protected void onResume(){super.onResume();handler.postDelayed(status,4000);}
 @Override protected void onPause(){handler.removeCallbacks(status);super.onPause();}
 @Override public void onBackPressed(){web.evaluateJavascript("document.querySelectorAll('dialog[open]').forEach(d=>d.close())",null);super.onBackPressed();}
 private void notifyJs(boolean active,String text){web.evaluateJavascript("window.nativeSharingStatus&&window.nativeSharingStatus("+active+","+JSONObject.quote(text)+")",null);}
 private void launch(){if(pending==null)return;try{startForegroundService(pending);notifyJs(true,"Starting GPS sharing…");}catch(Exception e){revokePending();notifyJs(false,"Unable to start sharing. Open the app and try again.");}pending=null;}
 private void revokePending(){if(pending==null)return;String api=pending.getStringExtra("api"),token=pending.getStringExtra("token");new Thread(()->{try{Network.request(api+"/api/session","DELETE",token,null);}catch(Exception ignored){}}).start();pending=null;}
 @Override public void onRequestPermissionsResult(int code,String[] permissions,int[] results){super.onRequestPermissionsResult(code,permissions,results);if(code==40){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)launch();else{revokePending();notifyJs(false,"Precise location permission is needed to contribute. Viewing still works.");}}}
 public class Bridge {
 @JavascriptInterface public boolean isSharing(){return TrackingService.running;}
 @JavascriptInterface public void startSharing(String api,String token,String trip,long until){runOnUiThread(()->{if(TrackingService.running){notifyJs(true,"Already sharing. Stop before starting another journey.");return;}try{Uri u=Uri.parse(api);if(!"https".equals(u.getScheme())||u.getHost()==null||u.getUserInfo()!=null||u.getQuery()!=null||u.getFragment()!=null)throw new Exception();pending=new Intent(MainActivity.this,TrackingService.class).putExtra("api",api).putExtra("token",token).putExtra("trip",trip).putExtra("until",until);if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){ArrayList<String> ps=new ArrayList<>();ps.add(Manifest.permission.ACCESS_FINE_LOCATION);ps.add(Manifest.permission.ACCESS_COARSE_LOCATION);if(Build.VERSION.SDK_INT>=33)ps.add(Manifest.permission.POST_NOTIFICATIONS);requestPermissions(ps.toArray(new String[0]),40);}else if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},40);}else launch();}catch(Exception e){notifyJs(false,"Use a valid HTTPS backend address.");}});}
 @JavascriptInterface public void stopSharing(){runOnUiThread(()->{stopService(new Intent(MainActivity.this,TrackingService.class));notifyJs(false,"Sharing stopped");});}
 }
}
