package in.railsaathi.app;
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.location.*;import android.content.pm.PackageManager;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicBoolean;import org.json.JSONObject;
public class TrackingService extends Service implements LocationListener {
 public static volatile boolean running=false;private LocationManager manager;private Location latest;private String api,token;private long until,lastUpload=0,uploadInterval=15000,nextAttempt=0;private boolean started=false;private String role="primary";private final Handler handler=new Handler(Looper.getMainLooper());private final ExecutorService executor=Executors.newSingleThreadExecutor();private final AtomicBoolean busy=new AtomicBoolean();
 private final Runnable tick=new Runnable(){public void run(){if(!running)return;if(System.currentTimeMillis()>=until){setStatus("Sharing session expired");stopSelf();return;}upload();handler.postDelayed(this,1000);}};
 @Override public void onCreate(){super.onCreate();manager=(LocationManager)getSystemService(LOCATION_SERVICE);NotificationChannel channel=new NotificationChannel("sharing","Train GPS sharing",NotificationManager.IMPORTANCE_LOW);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(channel);}
 private Notification notification(String text){Intent open=new Intent(this,MainActivity.class);PendingIntent content=PendingIntent.getActivity(this,0,open,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Intent stop=new Intent(this,TrackingService.class).setAction("STOP");PendingIntent action=PendingIntent.getService(this,1,stop,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,"sharing").setSmallIcon(in.railsaathi.app.R.drawable.ic_train).setContentTitle("RailSaathi · GPS sharing").setContentText(text).setContentIntent(content).setOngoing(true).addAction(new Notification.Action.Builder(null,"Stop sharing",action).build()).build();}
 private void setStatus(String s){getSharedPreferences("tracking",0).edit().putString("status",s).apply();if(running)((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(1,notification(s));}
 @Override public int onStartCommand(Intent intent,int flags,int id){if(intent==null){stopSelf();return START_NOT_STICKY;}if("STOP".equals(intent.getAction())){stopSelf();return START_NOT_STICKY;}if(started)return START_NOT_STICKY;started=true;api=intent.getStringExtra("api");token=intent.getStringExtra("token");until=Math.min(intent.getLongExtra("until",0),System.currentTimeMillis()+12*3600000L);if(api==null||token==null||until<=System.currentTimeMillis()){stopSelf();return START_NOT_STICKY;}startForeground(1,notification("Waiting for a precise GPS fix…"));running=true;if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){setStatus("Location permission unavailable");stopSelf();return START_NOT_STICKY;}try{if(!manager.isProviderEnabled(LocationManager.GPS_PROVIDER))setStatus("Enable phone GPS to share your train");manager.requestLocationUpdates(LocationManager.GPS_PROVIDER,5000,0,this,Looper.getMainLooper());handler.post(tick);}catch(Exception e){setStatus("Could not access GPS");stopSelf();}return START_NOT_STICKY;}
 @Override public void onLocationChanged(Location location){if(location.isFromMockProvider())return;latest=new Location(location);upload();}
 private void upload(){Location p=latest;if(p==null||p.getAccuracy()>150||SystemClock.elapsedRealtimeNanos()-p.getElapsedRealtimeNanos()>30000000000L){setStatus("Waiting for a precise GPS fix…");return;}long now=SystemClock.elapsedRealtime();long cadence="primary".equals(role)&&p.hasSpeed()&&p.getSpeed()>2?15000:uploadInterval;if(now<nextAttempt||(lastUpload!=0&&now-lastUpload<cadence)||!busy.compareAndSet(false,true))return;executor.execute(()->{try{JSONObject b=new JSONObject();b.put("lat",p.getLatitude());b.put("lon",p.getLongitude());b.put("accuracy",p.getAccuracy());b.put("timestamp",p.getTime());b.put("speed",p.hasSpeed()?p.getSpeed():JSONObject.NULL);b.put("bearing",p.hasBearing()?p.getBearing():JSONObject.NULL);JSONObject result=Network.request(api+"/api/positions","POST",token,b);handler.post(()->{if(!running)return;lastUpload=SystemClock.elapsedRealtime();nextAttempt=0;role=result.optString("role","primary");uploadInterval=result.optLong("uploadIntervalMs",15000);setStatus(!result.optBoolean("snapshotPublished",true)?"GPS received · public update delayed":"standby".equals(role)?"Backup contributor · every 60 seconds":result.optBoolean("stationary",false)?"Train stationary · every 60 seconds":"GPS sent · every 15 seconds");});}catch(Exception e){handler.post(()->{if(running){nextAttempt=SystemClock.elapsedRealtime()+15000;if(e instanceof Network.ApiException&&((Network.ApiException)e).status==401){setStatus("Sharing session ended");stopSelf();}else setStatus("Upload failed · retrying after 15 seconds");}});}finally{busy.set(false);}});}
 @Override public void onStatusChanged(String provider,int status,Bundle extras){}
 @Override public void onProviderEnabled(String provider){}
 @Override public void onProviderDisabled(String provider){setStatus("GPS disabled · enable location to continue");}
 @Override public void onDestroy(){running=false;handler.removeCallbacksAndMessages(null);if(manager!=null)manager.removeUpdates(this);getSharedPreferences("tracking",0).edit().putString("status","Sharing stopped").apply();if(token!=null&&api!=null)executor.execute(()->{try{Network.request(api+"/api/session","DELETE",token,null);}catch(Exception ignored){}});executor.shutdown();stopForeground(STOP_FOREGROUND_REMOVE);super.onDestroy();}
 @Override public IBinder onBind(Intent intent){return null;}
}
