export class TrainMap {
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.center=[77.21,28.61];this.zoom=12;this.tiles=new Map();this.route=null;this.position=null;this.follow=true;this.angle=0;this.point=null;const resize=()=>{const r=canvas.getBoundingClientRect();this.w=r.width;this.h=r.height;canvas.width=this.w*devicePixelRatio;canvas.height=this.h*devicePixelRatio;this.ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)};new ResizeObserver(resize).observe(canvas);let drag=null;canvas.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const c=this.world(this.center);this.center=this.geo([c[0]-(e.clientX-drag[0]),c[1]-(e.clientY-drag[1])]);drag=[e.clientX,e.clientY];this.follow=false});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();this.changeZoom(e.deltaY<0?1:-1)},{passive:false});this.frame=()=>{this.draw();requestAnimationFrame(this.frame)};requestAnimationFrame(this.frame)}
 world(p){const s=256*2**this.zoom,lat=Math.max(-85,Math.min(85,p[1]))*Math.PI/180;return [(p[0]+180)/360*s,(1-Math.log(Math.tan(lat)+1/Math.cos(lat))/Math.PI)/2*s]}
 geo(p){const s=256*2**this.zoom;return [p[0]/s*360-180,Math.atan(Math.sinh(Math.PI*(1-2*p[1]/s)))*180/Math.PI]}
 screen(p){const c=this.world(this.center),v=this.world(p);return [v[0]-c[0]+this.w/2,v[1]-c[1]+this.h/2]}
 changeZoom(d){this.zoom=Math.max(4,Math.min(17,this.zoom+d))}
 setTrain(p){this.position=p;if(!this.point)this.point=p.point.slice()}
 draw(){if(!this.w)return;const ctx=this.ctx,w=this.w,h=this.h;ctx.fillStyle='#e9eee9';ctx.fillRect(0,0,w,h);const c=this.world(this.center),left=c[0]-w/2,top=c[1]-h/2,n=2**this.zoom;for(let y=Math.floor(top/256);y<=Math.floor((top+h)/256);y++)for(let x=Math.floor(left/256);x<=Math.floor((left+w)/256);x++){if(y<0||y>=n)continue;const xx=((x%n)+n)%n,key=`${this.zoom}/${xx}/${y}`;let tile=this.tiles.get(key);if(!tile){tile=new Image();tile.referrerPolicy='strict-origin-when-cross-origin';tile.src=`https://tile.openstreetmap.org/${key}.png`;this.tiles.set(key,tile);if(this.tiles.size>160)this.tiles.delete(this.tiles.keys().next().value)}if(tile.complete&&tile.naturalWidth)ctx.drawImage(tile,x*256-left,y*256-top,256,256)}
 if(this.route){ctx.beginPath();this.route.forEach((p,i)=>{const a=this.screen(p);i?ctx.lineTo(...a):ctx.moveTo(...a)});ctx.strokeStyle='#ffffff';ctx.lineWidth=9;ctx.stroke();ctx.strokeStyle='#117c76';ctx.lineWidth=5;ctx.stroke()}
 if(this.position){const t=this.position;this.point=this.point.map((v,i)=>v+(t.point[i]-v)*.035);this.angle+=((t.bearing-this.angle+540)%360-180)*.06;if(this.follow)this.center=this.point.slice();const [x,y]=this.screen(this.point);ctx.fillStyle=t.stale?'#a87732':'#138b8040';ctx.beginPath();ctx.arc(x,y,29,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(x,y);ctx.rotate(this.angle*Math.PI/180);ctx.shadowColor='#153c3c55';ctx.shadowBlur=10;ctx.fillStyle=t.stale?'#a87732':'#086e66';ctx.beginPath();ctx.roundRect(-13,-24,26,44,8);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='white';ctx.beginPath();ctx.roundRect(-8,-16,16,12,3);ctx.fill();ctx.fillRect(-7,2,14,3);ctx.fillRect(-7,8,14,3);ctx.beginPath();ctx.moveTo(0,-34);ctx.lineTo(-7,-26);ctx.lineTo(7,-26);ctx.closePath();ctx.fill();ctx.restore()}
 }
}
